spring:
  application:
    name: "@project.name@"
  datasource:
    url: jdbc:mysql://localhost:3307/payment_service?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    com.compass.pb.exams.orders: DEBUG